- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'test'
    subscriptionId: 'c3bffe7f-e643-4393-ae69-ab6e9fd0668f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-ls-amitabha-das2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'